import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/sidebar/AppSide";
import Header from "@/components/header/Header";
import Providers from "@/redux/features/Providers";
import { Toaster } from "sonner";
import AppInitializer from "@/components/AppInitializer/AppInitializer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chakra Quiz - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AppInitializer>
            <Toaster position='top-right' richColors />
            <SidebarProvider>
              <div
                className='flex min-h-screen bg-bodyBg w-full'
                style={{
                  background:
                    "linear-gradient(180deg, #315D62 0%, #6ECEDA 100%)",
                }}
              >
                <AppSidebar />
                <main className='relative flex-1 min-h-screen w-full bg-body-bg p-6'>
                  <SidebarTrigger className='text-black' />
                  <Header />
                  {children}
                </main>
              </div>
            </SidebarProvider>
          </AppInitializer>
        </Providers>
      </body>
    </html>
  );
}
